name: Deploy Develop Branch to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_MAIN_HOST_IP }}
          username: git_user
          key: ${{ secrets.SSH_MAIN_PRIVATE_KEY }}
          script: |
            cd /home/git_user/workspace/Asksource
            git checkout main
            git pull
            sudo systemctl restart asksource.service
            echo "Waiting..."
            sleep 20

            for i in {1..6}; do
              if ss -tuln | grep -q ':80'; then
                echo "✅ Port 80 is now active."
                break
              else
                echo "⏳ Port 80 not ready yet. Retrying in 80 seconds..."
                sleep 80
              fi
            done

            if ! ss -tuln | grep -q ':80'; then
              echo "❌ Service failed to start on port 80"
              exit 1
            fi